amosproj/amos-ss2021-project2-context-map

.gitattributes
frontend/package-lock.json

Fix for #39

---

.github/workflows/frontend-build.yml
.github/workflows/frontend-tests-e2e.yml
.github/workflows/frontend-tests-unit.yml

This PR fixes the CI network timeouts as described by #79

Fix CI network timeouts

---

build/start-backend-dbg.sh
build/start-database.sh
build/start-frontend-dbg.sh

This PR adds `sh` run scripts for linux enivronments without the powershell installed.
Don't know who to assign, so anyone having a linux system, please review.

Linux run scripts

---

frontend/cypress/unit/FakeDataSchemaService.test.js
frontend/src/configureServices.ts
frontend/src/services/schema/FakeDataSchemaService.ts
frontend/src/services/schema/SchemaService.ts
frontend/src/services/schema/SchemaServiceImpl.ts
frontend/src/services/schema/index.ts
frontend/src/utils/AsyncLazy.ts

This PR implemented the schema service in the frontend that retrieves the schema information via the backend API. Closes #100

Schema service

---

frontend/src/Layout.tsx
frontend/src/visualization/Graph.tsx
frontend/src/visualization/filtering/Filter.tsx
frontend/src/visualization/filtering/components/EntityFilterElement.tsx
frontend/src/visualization/shared-ops/FetchData.tsx

This PR contributes to #47 by adding property-values to the filter-UI (#105) and adjusts the filtering to a toggable sidebar.

Filter use async

---

backend/src/filter/EntityFilterConditionExecutor.ts
backend/src/filter/NodeFilterConditionExecutor.ts
backend/src/filter/filter.controller.ts
backend/src/filter/filter.service.base.ts
backend/src/utils/any.ts
backend/tests/fixtures/filter/FilterServicMock.ts
backend/tests/unit/filter/filter.controller.spec.ts

See #107 
There is still an issue that the query service cannot handle exact numeric filtering. This is tracked by #155 and will be fixed in a follow up.

Controller and tests for filter queries

---

frontend/src/services/filter/FilterService.ts
frontend/src/services/filter/FilterServiceImpl.ts

This PR adds the frontend filter query service API and impl that is needed to close #107.

Frontend filter query service

---

frontend/src/errors/ErrorBoundary.tsx
frontend/src/errors/ErrorComponent.tsx
frontend/src/errors/useDefaultErrorHandler.ts
frontend/src/routing/routes.tsx

Error boundary promises

---

frontend/src/search/SearchEntryConverter.tsx
frontend/src/search/SearchResultList.ts
frontend/src/search/Searchbar.scss
frontend/src/search/Searchbar.tsx

Closes #180. Closes #128.
Closes #92.
Closes #30.

Search Error Handling + Routing

---

frontend/src/App.tsx
frontend/src/Layout.tsx
frontend/src/home/Home.css
frontend/src/visualization/dashboard-card/cardContents.tsx
frontend/src/visualization/filtering/components/dialog/EntityPropertySelect.tsx

This PR adds some formatting fixes. (Small part of #198)

Formatting fixes

---

frontend/src/configureServices.ts
frontend/src/stores/FilterStore.ts
frontend/src/stores/GraphDataStore.ts
frontend/src/stores/SimpleStore.ts
frontend/src/utils/useObservable.ts
frontend/src/visualization/Graph.tsx
frontend/src/visualization/filtering/Filter.tsx

Data Store

---

backend/package.json
frontend/package.json
package.json

Renamed projects

---

frontend/src/utils/useObservable.ts
frontend/src/visualization/filtering/MaxEntitiesSlider.tsx

Modifies useObservable so that it can be used with useState directly

useObservable with useState

---

frontend/cypress/unit/stores/colors/EdgeColorStore.test.ts
frontend/cypress/unit/stores/colors/NodeColorStore.test.ts
frontend/cypress/unit/stores/colors/getNthColor.test.ts
frontend/src/stores/colors/BaseEntityColorStore.ts
frontend/src/stores/colors/EdgeColorStore.ts
frontend/src/stores/colors/EntityVisualisationAttributes.ts
frontend/src/stores/colors/NodeColorStore.ts
frontend/src/stores/colors/getNthColor.ts
frontend/src/stores/colors/index.ts

Dummy implementation for stores so we can start with the UI implementation #251.
Closes #250

Entity color stores

---

frontend/src/stores/colors/EntityColorStore.ts
frontend/src/stores/colors/EntityVisualisationAttributes.ts
frontend/src/stores/colors/getTextColor.ts

Adds coloring for subsidiaries.
Adds text color for nodes.

Color store subsidaries

---

frontend/cypress/integration/visualization/shortestPath.e2e.js
frontend/package.json
frontend/src/visualization/filtering/Filter.tsx
frontend/src/visualization/filtering/ShortestPathMenu.tsx
frontend/src/visualization/filtering/ShortestPathNodeSelection.tsx
frontend/yarn.lock

This PR adds the UI in the filter menu for calculating the shortest path of #232.

Filter shortest path

---

frontend/cypress/unit/stores/exploration/ExplorationStore.test.ts
frontend/src/configureServices.ts
frontend/src/stores/exploration/ExplorationQuestions.ts
frontend/src/stores/exploration/ExplorationStore.ts
frontend/src/stores/exploration/calculateScore.ts
frontend/src/stores/exploration/index.ts
frontend/src/stores/exploration/interfaces/ExplorationAnswer.ts
frontend/src/stores/exploration/interfaces/ExplorationQuestion.ts
frontend/src/stores/exploration/interfaces/ExplorationWeight.ts
frontend/src/utils/DeepReadonly.ts

Exploration Store

---

frontend/src/exploration/Exploration.tsx
frontend/src/exploration/previews/Previews.tsx
frontend/src/exploration/questions/Questions.tsx

Creates skeleton of exploration page so we can implement left and right side of it without merge conflicts.

Skeleton exploration page

---

frontend/cypress/integration/visualization/filter.e2e.js
frontend/src/stores/FilterQueryStore.ts
frontend/src/stores/filterState/FilterStateStore.ts
frontend/src/visualization/filtering/Filter.tsx
frontend/src/visualization/filtering/FilterLine.tsx
frontend/src/visualization/filtering/FilterLineProperties.tsx
frontend/src/visualization/filtering/FilterLineProperty.tsx

Filter refactoring tests

---

frontend/src/visualization/dashboard-card/DashboardCard.tsx

Fixes Dashboard links

---

.github/workflows/deploy.yml
deploy.sh
frontend/src/home/Home.tsx
upload-artifacts.sh

adds github actions workflow for #282. Not ready for review yet

Deployment actions

---

frontend/src/exploration/previews/Previews.tsx

reverse exploration page preview order (#348)

---

frontend/src/stores/colors/EntityStyleProviderImpl.ts
frontend/src/stores/colors/EntityStyleStore.ts
frontend/src/visualization/Graph.tsx

Resolves
> * when not in filtered graph, show warning
from #234

Search not found warning

---

frontend/cypress/integration/visualization/filter.e2e.js
frontend/src/stores/filterState/FilterState.ts
frontend/src/stores/filterState/FilterStateStore.ts
frontend/src/visualization/filtering/FilterLine.tsx
frontend/src/visualization/filtering/FilterLineProperties.tsx
frontend/src/visualization/filtering/FilterLineProperty.tsx

Adds user story #347 and rearranges the FilterStateStore and FilterState.

Filter selection

---

frontend/src/configureServices.ts
frontend/src/stores/SchemaStore.ts
frontend/src/stores/filterState/FilterStateStore.ts
frontend/src/visualization/filtering/Filter.tsx

Filter enhancement

---

frontend/src/visualization/filtering/FilterLine.tsx

Finishes #347 by adding an icon to the FilterLine button which signals whether the line is active

Frontend add "Add" and "Remove" Icon in FilterLine.tsx

---

frontend/src/visualization/Visualization.tsx
frontend/src/visualization/dashboard-card/DashboardCard.tsx

cleans up code and applies same height to all dashboard items

clean up dashboard layout

---

frontend/src/visualization/dashboard-card/cardContents.tsx

This PR implements dashboard text corrections requested by the POs

correct dashboard text

---

frontend/src/data/Data.tsx
frontend/src/search/Searchbar.tsx
frontend/src/stores/SearchSelectionStore.ts
frontend/src/stores/colors/EntityStyleStore.ts
frontend/src/visualization/Graph.tsx

search: missing steps

---

frontend/package.json
frontend/src/App.tsx
frontend/src/stores/QueryResultStore.ts
frontend/src/visualization/Graph.tsx
frontend/yarn.lock

Shortest path warning

---

frontend/src/Layout.tsx
frontend/src/search/Searchbar.scss

Tab layout fix

---

frontend/cypress/fixtures/QueryServiceFake.ts
frontend/cypress/fixtures/entityDetails/entityDetails.ts
frontend/cypress/unit/stores/entityDetails/EntityDetailsStore.test.ts

Adds tests for the EntityDetailsStore, still WIP

add more tests

---

frontend/src/home/HomeVideoModal.tsx

adjust youtube link to new video

---

frontend/src/visualization/pages/GraphDetails.tsx

Limit node details width

---

frontend/src/visualization/filtering/MaxEntitiesSlider.tsx

important comment adjustment, that was overlooked in #403 :upside_down_face:

adjust comment to new condition
